service: stripe-api-product
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["Product", "Arn"] }

plugins:
  - serverless-offline

functions:
  createProduct:
    handler: product/handlers/createProduct.createProduct
    events:
      - httpApi:
          path: /product
          method: post
  getProduct:
    handler: product/handlers/getProduct.getProduct
    events:
      - httpApi:
          path: /product/{id}
          method: get
  updateProduct:
    handler: product/handlers/updateProduct.updateProduct
    events:
      - httpApi:
          path: /product/{id}
          method: put
  deleteProduct:
    handler: product/handlers/deleteProduct.deleteProduct
    events:
      - httpApi:
          path: /product/{id}
          method: delete
  listProduct:
    handler: product/handlers/listProduct.listProduct
    events:
      - httpApi:
          path: /products
          method: get
